import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import '../../models/job.dart';
import '../../models/job_image.dart';
import '../../models/job_message.dart';
import '../../models/user.dart';
import '../../services/auth_service.dart';
import '../../services/job_service.dart';
import '../../services/chat_service.dart';
import '../../services/storage_service.dart';
import '../../services/pdf_service.dart';
import '../../services/theme_localization_service.dart';
import '../widgets/base_screen.dart';
import '../widgets/glass_card.dart';
import 'add_subtask_page.dart';
import 'log_hours_page.dart';
import '../../models/route_point.dart';
import 'package:url_launcher/url_launcher.dart';

class JobDetailsPage extends StatefulWidget {
  final String jobId;
  const JobDetailsPage({super.key, required this.jobId});

  @override
  State<JobDetailsPage> createState() => _JobDetailsPageState();
}

class _JobDetailsPageState extends State<JobDetailsPage> with SingleTickerProviderStateMixin {
  late TabController _tabController;
  final _jobService = JobService();
  final _chatService = ChatService();
  final _pdfService = PdfService();
  final _messageController = TextEditingController();
  final _scrollController = ScrollController();
  final _picker = ImagePicker();
  
  bool _isUploadingPhoto = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  // --- Subtask Actions ---
  Future<void> _toggleSubtask(String subtaskId, bool isCompleted) async {
    try {
      await _jobService.toggleSubtask(widget.jobId, subtaskId, isCompleted);
    } catch (e) {
      debugPrint('Error toggling subtask: $e');
    }
  }

  // --- Chat Actions ---
  Future<void> _sendMessage(String senderId, String senderName) async {
    final text = _messageController.text.trim();
    if (text.isEmpty) return;

    try {
      final msg = JobMessage(
        id: '', // Generated by Firebase
        jobId: widget.jobId,
        senderId: senderId,
        senderName: senderName,
        text: text,
        timestamp: DateTime.now(),
      );

      _messageController.clear();
      await _chatService.sendMessage(msg);
      
      // Scroll to bottom
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent + 60,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    } catch (e) {
      debugPrint('Error sending message: $e');
    }
  }

  // --- Photo Actions ---
  Future<void> _addPhoto(String userName) async {
    try {
      final pickedFile = await _picker.pickImage(
        source: ImageSource.camera,
        maxWidth: 800,
        maxHeight: 800,
        imageQuality: 80,
      );

      if (pickedFile == null) return;

      setState(() {
        _isUploadingPhoto = true;
      });

      final bytes = await pickedFile.readAsBytes();
      final storageService = StorageService();
      final fileName = '${widget.jobId}_${DateTime.now().millisecondsSinceEpoch}.jpg';
      final downloadUrl = await storageService.uploadImage(bytes, fileName);

      final jobImage = JobImage(
        id: '', // Push key
        jobId: widget.jobId,
        url: downloadUrl,
        uploadedBy: userName,
        uploadedAt: DateTime.now(),
      );

      await _jobService.addJobImage(widget.jobId, jobImage);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(context.tr('ImageUploadedSuccess'))),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('${context.tr('ImageUploadError')}: $e')),
        );
      }
    } finally {
      setState(() {
        _isUploadingPhoto = false;
      });
    }
  }

  // --- Job Complete Actions ---
  Future<void> _handleCompleteJob(String userId, String userName) async {
    try {
      await _jobService.completeJob(widget.jobId, userId, userName);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(context.tr('JobCompletedSuccess'))),
        );
      }
    } catch (e) {
      debugPrint('Error completing job: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    final provider = Provider.of<ThemeAndLocalizationProvider>(context);
    final authService = Provider.of<AuthService>(context);
    final user = authService.currentUser;

    if (user == null) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }

    return StreamBuilder<Job?>(
      stream: _jobService.streamJob(widget.jobId),
      builder: (context, snapshot) {
        final job = snapshot.data;
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const BaseScreen(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        if (job == null) {
          return BaseScreen(
            title: context.tr('NotFoundTitle'),
            body: Center(
              child: Text(
                'Job not found',
                style: TextStyle(color: provider.textPrimaryColor, fontSize: 18),
              ),
            ),
          );
        }

        return Scaffold(
          body: BaseScreen(
            title: job.title,
            actions: [
              IconButton(
                icon: const Icon(Icons.share),
                onPressed: () => _pdfService.generateAndShareJobReport(
                  job,
                  job.subtaskList,
                  job.imageList,
                ),
              ),
            ],
            body: Column(
              children: [
                // Custom TabBar inside a Glass Card
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16.0),
                  child: GlassCard(
                    padding: const EdgeInsets.all(4),
                    borderRadius: 12,
                    child: TabBar(
                      controller: _tabController,
                      indicatorColor: provider.primaryColor,
                      labelColor: provider.primaryColor,
                      unselectedLabelColor: provider.textSecondaryColor,
                      indicatorSize: TabBarIndicatorSize.tab,
                      tabs: [
                        Tab(text: context.tr('JobDetailsLabel').split(' ').first),
                        Tab(text: context.tr('SubTask').replaceAll('SubTask', 'Tasks')),
                        const Tab(text: 'Chat'),
                        Tab(text: context.tr('Images')),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 12),

                // TabBar View Content
                Expanded(
                  child: TabBarView(
                    controller: _tabController,
                    children: [
                      // --- TAB 1: INFO ---
                      _buildInfoTab(job, user, provider),

                      // --- TAB 2: SUBTASKS ---
                      _buildSubtasksTab(job, user, provider),

                      // --- TAB 3: CHAT ---
                      _buildChatTab(job, user, provider),

                      // --- TAB 4: GALLERY ---
                      _buildGalleryTab(job, user, provider),
                    ],
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  // Info Tab Widget Builder
  Widget _buildInfoTab(Job job, AppUser user, ThemeAndLocalizationProvider provider) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Details General Card
          GlassCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  job.title,
                  style: TextStyle(color: provider.textPrimaryColor, fontSize: 20, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 8),
                Text(
                  context.tr('DescriptionFormat', [job.description]),
                  style: TextStyle(color: provider.textSecondaryColor, fontSize: 14),
                ),
                const Divider(color: Colors.white24, height: 24),
                Row(
                  children: [
                    Icon(Icons.location_on, color: provider.primaryColor, size: 20),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        job.address,
                        style: TextStyle(color: provider.textPrimaryColor, fontSize: 14),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                Row(
                  children: [
                    Icon(Icons.vpn_key, color: provider.primaryColor, size: 20),
                    const SizedBox(width: 8),
                    Text(
                      context.tr('JobCodeFormat', [job.jobCode]),
                      style: TextStyle(color: provider.textPrimaryColor, fontSize: 14, fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // Workers List Card
          GlassCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  context.tr('WorkforceList'),
                  style: TextStyle(color: provider.textPrimaryColor, fontSize: 16, fontWeight: FontWeight.bold),
                ),
                const Divider(color: Colors.white24, height: 16),
                if (job.assignedWorkers.isEmpty)
                  Text(
                    context.tr('NoWorkersFound').replaceAll('No workers found.', 'No workers assigned yet.'),
                    style: TextStyle(color: provider.textSecondaryColor, fontStyle: FontStyle.italic),
                  )
                else
                  ...job.assignedWorkers.values.map(
                    (workerName) => Padding(
                      padding: const EdgeInsets.symmetric(vertical: 4.0),
                      child: Row(
                        children: [
                          Icon(Icons.person, size: 16, color: provider.secondaryColor),
                          const SizedBox(width: 8),
                          Text(workerName, style: TextStyle(color: provider.textPrimaryColor, fontSize: 14)),
                        ],
                      ),
                    ),
                  ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Primary Actions
          if (user.role == 'Worker' && !job.isCompleted) ...[
            ElevatedButton.icon(
              onPressed: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => LogHoursPage(jobId: job.id)),
                );
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: provider.primaryColor,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              icon: const Icon(Icons.timer),
              label: Text(context.tr('LogHours')),
            ),
            const SizedBox(height: 12),
          ],

          if (user.role == 'Foreman' && !job.isCompleted) ...[
            ElevatedButton.icon(
              onPressed: () => _handleCompleteJob(user.id, user.displayName),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.green.shade700,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              icon: const Icon(Icons.check_circle),
              label: Text(context.tr('CompleteJob')),
            ),
            const SizedBox(height: 12),
          ],

          // Snowracer Specific Route Trigger
          if (job.jobType == 'Snowracer') ...[
            ElevatedButton.icon(
              onPressed: () {
                Navigator.pushNamed(
                  context,
                  '/snowracer_live',
                  arguments: job.id,
                );
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.cyan.shade700,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              icon: const Icon(Icons.ac_unit),
              label: Text(context.tr('StartSnowracer')),
            ),
            const SizedBox(height: 12),
            ElevatedButton.icon(
              onPressed: () async {
                if (job.routePoints.isNotEmpty) {
                  final points = List<RoutePoint>.from(job.routePoints)
                    ..sort((a, b) => a.order.compareTo(b.order));
                  
                  final origin = points.first;
                  final destination = points.last;

                  String waypoints = '';
                  if (points.length > 2) {
                    final waypointPoints = points.sublist(1, points.length - 1);
                    waypoints = '&waypoints=' + waypointPoints
                        .map((p) => '${p.latitude},${p.longitude}')
                        .join('%7C');
                  }

                  final urlStr = 'https://www.google.com/maps/dir/?api=1'
                      '&origin=${origin.latitude},${origin.longitude}'
                      '&destination=${destination.latitude},${destination.longitude}'
                      '$waypoints'
                      '&travelmode=driving';

                  final uri = Uri.parse(urlStr);
                  try {
                    if (await canLaunchUrl(uri)) {
                      await launchUrl(uri, mode: LaunchMode.externalApplication);
                    } else {
                      if (context.mounted) {
                        ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(content: Text(context.tr('NoRouteMessage'))),
                        );
                      }
                    }
                  } catch (e) {
                    debugPrint('Error launching map: $e');
                  }
                } else {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text(context.tr('NoRouteMessage'))),
                  );
                }
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: provider.secondaryColor,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              icon: const Icon(Icons.map),
              label: Text(context.tr('ViewFullRouteMap')),
            ),
            const SizedBox(height: 12),
          ],

        ],
      ),
    );
  }

  // Subtasks Tab Widget Builder
  Widget _buildSubtasksTab(Job job, AppUser user, ThemeAndLocalizationProvider provider) {
    final subtasks = job.subtaskList;
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Subtask Header Row
          const SizedBox(height: 10),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('SubtasksRoute').split('/').first.trim(),
                style: TextStyle(color: provider.textPrimaryColor, fontSize: 18, fontWeight: FontWeight.bold),
              ),
              if (user.role == 'Foreman' && !job.isCompleted)
                TextButton.icon(
                  onPressed: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => AddSubtaskPage(jobId: job.id)),
                    );
                  },
                  icon: const Icon(Icons.add_task),
                  label: Text(context.tr('AddSubtask')),
                  style: TextButton.styleFrom(foregroundColor: provider.primaryColor),
                ),
            ],
          ),
          const SizedBox(height: 16),

          // Checkbox List
          Expanded(
            child: subtasks.isEmpty
                ? Center(
                    child: Text(
                      context.tr('NoSubtasksMessage'),
                      style: TextStyle(color: provider.textSecondaryColor, fontSize: 14),
                    ),
                  )
                : ListView.builder(
                    itemCount: subtasks.length,
                    itemBuilder: (context, index) {
                      final sub = subtasks[index];
                      return Padding(
                        padding: const EdgeInsets.only(bottom: 12.0),
                        child: GlassCard(
                          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                          child: CheckboxListTile(
                            title: Text(
                              sub.title,
                              style: TextStyle(
                                color: provider.textPrimaryColor,
                                fontWeight: FontWeight.bold,
                                decoration: sub.isCompleted ? TextDecoration.lineThrough : null,
                              ),
                            ),
                            subtitle: Text(
                              sub.description,
                              style: TextStyle(color: provider.textSecondaryColor),
                            ),
                            value: sub.isCompleted,
                            activeColor: provider.primaryColor,
                            checkColor: Colors.white,
                            onChanged: job.isCompleted
                                ? null
                                : (bool? value) {
                                    if (value != null) {
                                      _toggleSubtask(sub.id, value);
                                    }
                                  },
                            secondary: IconButton(
                              icon: Icon(Icons.map, color: provider.primaryColor),
                              onPressed: () async {
                                if ((sub.address == null || sub.address!.isEmpty) &&
                                    (sub.latitude == 0 && sub.longitude == 0)) {
                                  if (mounted) {
                                    ScaffoldMessenger.of(context).showSnackBar(
                                      SnackBar(content: Text(context.tr('NoSubtaskLocationMessage'))),
                                    );
                                  }
                                  return;
                                }

                                String url = '';
                                if (sub.address != null && sub.address!.isNotEmpty) {
                                  url = 'https://www.google.com/maps/dir/?api=1&destination=${Uri.encodeComponent(sub.address!)}&travelmode=driving';
                                } else if (sub.latitude != 0 && sub.longitude != 0) {
                                  url = 'https://www.google.com/maps/dir/?api=1&destination=${sub.latitude},${sub.longitude}&travelmode=driving';
                                }

                                if (url.isNotEmpty) {
                                  final uri = Uri.parse(url);
                                  try {
                                    if (await canLaunchUrl(uri)) {
                                      await launchUrl(uri, mode: LaunchMode.externalApplication);
                                    } else {
                                      if (mounted) {
                                        ScaffoldMessenger.of(context).showSnackBar(
                                          SnackBar(content: Text(context.tr('NoSubtaskLocationMessage'))),
                                        );
                                      }
                                    }
                                  } catch (e) {
                                    debugPrint('Error launching map: $e');
                                  }
                                }
                              },
                            ),
                            controlAffinity: ListTileControlAffinity.leading,

                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }

  // Chat Tab Widget Builder (Syncs in real-time)
  Widget _buildChatTab(Job job, AppUser user, ThemeAndLocalizationProvider provider) {
    return StreamBuilder<List<JobMessage>>(
      stream: _chatService.streamMessages(job.id),
      builder: (context, snapshot) {
        final messages = snapshot.data ?? [];

        return Column(
          children: [
            Expanded(
              child: messages.isEmpty
                  ? Center(
                      child: Text(
                        'No messages yet. Send a message to start.',
                        style: TextStyle(color: provider.textSecondaryColor, fontSize: 14),
                      ),
                    )
                  : ListView.builder(
                      controller: _scrollController,
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                      itemCount: messages.length,
                      itemBuilder: (context, index) {
                        final msg = messages[index];
                        final isMe = msg.senderId == user.id;
                        return Align(
                          alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
                          child: Container(
                            margin: const EdgeInsets.only(bottom: 8),
                            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                            decoration: BoxDecoration(
                              color: isMe 
                                  ? provider.primaryColor.withOpacity(0.8) 
                                  : provider.surfaceColor,
                              borderRadius: BorderRadius.only(
                                topLeft: const Radius.circular(16),
                                topRight: const Radius.circular(16),
                                bottomLeft: isMe ? const Radius.circular(16) : Radius.zero,
                                bottomRight: isMe ? Radius.zero : const Radius.circular(16),
                              ),
                              border: Border.all(color: provider.borderColor),
                            ),
                            constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                if (!isMe)
                                  Text(
                                    msg.senderName,
                                    style: const TextStyle(color: Colors.cyanAccent, fontWeight: FontWeight.bold, fontSize: 12),
                                  ),
                                Text(
                                  msg.text,
                                  style: const TextStyle(color: Colors.white, fontSize: 14),
                                ),
                                const SizedBox(height: 4),
                                Align(
                                  alignment: Alignment.bottomRight,
                                  child: Text(
                                    DateFormat('HH:mm').format(msg.timestamp),
                                    style: const TextStyle(color: Colors.white60, fontSize: 10),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
            ),
            // Message input field
            if (!job.isCompleted)
              Padding(
                padding: const EdgeInsets.all(12.0),
                child: GlassCard(
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  borderRadius: 24,
                  child: Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: _messageController,
                          style: const TextStyle(color: Colors.white),
                          decoration: InputDecoration(
                            hintText: context.tr('TypeAMessage'),
                            hintStyle: TextStyle(color: provider.textSecondaryColor),
                            border: InputBorder.none,
                            contentPadding: const EdgeInsets.symmetric(horizontal: 16),
                          ),
                        ),
                      ),
                      IconButton(
                        icon: Icon(Icons.send, color: provider.primaryColor),
                        onPressed: () => _sendMessage(user.id, user.displayName),
                      ),
                    ],
                  ),
                ),
              ),
          ],
        );
      },
    );
  }

  // Gallery Tab Widget Builder
  Widget _buildGalleryTab(Job job, AppUser user, ThemeAndLocalizationProvider provider) {
    final images = job.imageList;
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const SizedBox(height: 10),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                context.tr('Images'),
                style: TextStyle(color: provider.textPrimaryColor, fontSize: 18, fontWeight: FontWeight.bold),
              ),
              if (!job.isCompleted)
                ElevatedButton.icon(
                  onPressed: _isUploadingPhoto ? null : () => _addPhoto(user.displayName),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: provider.primaryColor,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                  icon: _isUploadingPhoto
                      ? const SizedBox(
                          height: 14,
                          width: 14,
                          child: CircularProgressIndicator(strokeWidth: 2, valueColor: AlwaysStoppedAnimation(Colors.white)),
                        )
                      : const Icon(Icons.camera_alt, size: 16),
                  label: Text(context.tr('AddPhoto')),
                ),
            ],
          ),
          const SizedBox(height: 16),

          Expanded(
            child: images.isEmpty
                ? Center(
                    child: Text(
                      context.tr('NoImages'),
                      style: TextStyle(color: provider.textSecondaryColor, fontSize: 14),
                    ),
                  )
                : GridView.builder(
                    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 3,
                      crossAxisSpacing: 10,
                      mainAxisSpacing: 10,
                    ),
                    itemCount: images.length,
                    itemBuilder: (context, index) {
                      final img = images[index];
                      return ClipRRect(
                        borderRadius: BorderRadius.circular(12),
                        child: InkWell(
                          onTap: () {
                            // Full-screen view or launch Editor
                            Navigator.pushNamed(
                              context,
                              '/image_editor',
                              arguments: {
                                'JobId': job.id,
                                'ImagePath': img.url,
                              },
                            );
                          },
                          child: Image.network(
                            img.url,
                            fit: BoxFit.cover,
                            loadingBuilder: (context, child, loadingProgress) {
                              if (loadingProgress == null) return child;
                              return Container(
                                color: Colors.black12,
                                child: const Center(child: CircularProgressIndicator(strokeWidth: 2)),
                              );
                            },
                          ),
                        ),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
